### ISSUE TITLE
Support argument counters

### ISSUE THREAD

**Issue by BradleyChatha** [BradleyChatha/jcli#16]
For example, `-v -v -v` would increment `-v` 3 times.

Even though we don't support the combined flag syntax (`-vvv`), in this specific case, since it'd need special casing anyway, we'd be able to support the logic for it.

The parser would provide us with `[(ShortHandArg, "v"), (Text, "vv")]` in the above case, so we could just check that the second token given to use only contains the same character as the argument name.

**Comment by andrey-zherikov** [comment]
I think it makes sense to make this more flexible. Take a look at pythons' [argparse.action](https://docs.python.org/3/library/argparse.html#action) - `'count'` is what you want to do but it's the only one possible action among others.

**Comment by BradleyChatha** [comment]
It's again down to what design to go with.

A UDA with a string passed to it? (I'm rather against magical strings).

A unique UDA per action?

A UDA with an enum passed to it (instead of a string)?

I'm kind of leaning towards the the third option.
