### ISSUE TITLE
Add pre-made validators.

### ISSUE THREAD

**Issue by BradleyChatha** [BradleyChatha/jcli#19]
Names are subject to change:
- [ ] MatchesRegex (Pre/post; strings) - Ensures the string matches the given regex.
- [ ] OneOf (post; any) -> Ensures that the value can be found within a predefined list.
- [ ] MaxSize (post; any[]) -> Ensures that the array doesn't go beyond the given size.
- [ ] InRange (post; numeric) -> Ensures that the number is within a certain range.
- [ ] Contains (post; any[]) -> Ensures that the array contains a certain value.

**Comment by andrey-zherikov** [comment]
Frankly speaking I see no point doing this (at least right now).

**Comment by BradleyChatha** [comment]
I don't care about this anymore, the user can make their own.
