### ISSUE TITLE
Add @PreValidate and @PostValidate

### ISSUE THREAD

**Issue by BradleyChatha** [BradleyChatha/jcli#24]
See https://github.com/BradleyChatha/jcli/pull/5/files/fe06787d5c6e03e9a3b67499e2547dbf4fcb916b#r517461699

**Comment by andrey-zherikov** [comment]
What do you think about this implementation?
```d
struct CommandNamedArg
{
    string name;
    string description;

    void function() pre_v;
    void function() post_v;
    
    auto PreValidate (void function() f) {  pre_v = f; return this; }
    auto PostValidate(void function() f) { post_v = f; return this; }
}

@(CommandNamedArg("name","description")
.PreValidate({writeln("a");})
.PreValidate({writeln("b");})
.PostValidate({writeln("c");})
)
int i;

pragma(msg, __traits(getAttributes, i));
pragma(msg, getUDAs!(i, CommandNamedArg));
```

This won't allow using `PreValidate`/`PostValidate` without `CommandNamedArg`.

**Comment by BradleyChatha** [comment]
Now there'd be two different places and mechanisms where user-defined validation take place: One inside `ArgBinder.bind`, and another somewhere within `CommandLineInterface`.

As mentioned in my other reply, arg binding is actually an isolated thing that `CommandLineInterface` is built on top of.

Adding in more functionality for what ends up being nothing more than a slight change in semantics isn't worth doing IMO.
