### ISSUE TITLE
How should global configuration be passed into `CommandLineInterface`

### ISSUE THREAD

**Issue by BradleyChatha** [BradleyChatha/jcli#32]
e.g. Case sensitivity (#14); default behaviour for redefined args (#15); and maybe also #31.

While my initial thought is to create a configuration struct the user can pass in, we need to keep in mind that certain commands, for whatever reason, may want different configuration values.

**Comment by andrey-zherikov** [comment]
If I understand you correctly then you want to have two types of configuration: parser config and command settings. The latter can override some settings from the former but not all (for example, it doesn't make sense to mix case sensitivity IMO). So you can have UDA that stores settings for each command (it's even possible to add a member to `@Command`.

I'd suggest to think about what pieces you want to configure. IMO:
- "redefined args" should be handled on per-arg basis and shouldn't be exposed as a global config
- bash completion should available through separate API
- case sensitivity is a definitely global parser setting

**Comment by BradleyChatha** [comment]
Parsing settings/anything to do strictly with `CommandLineInterface` are passed via `CommandLineSettings`.

Everything else will likely be UDAs.
