### ISSUE TITLE
Support of '-- <args>'

### ISSUE THREAD

**Issue by andrey-zherikov** [BradleyChatha/jcli#4]
The following use cases should be supported:
```
mytool <args> ... -- <other-args>
mytool subcommand <args> ... -- <other-args>
```

The usage of `<other-args>` is simple: they should not be parsed and should be stored as-is (they are usually passed to underlying tool).

Note that not all subcommands might use this feature.

**Comment by BradleyChatha** [comment]
JCLI already supports this feature, although until you pointed it out, it was in a bit of a rough state, so I've gone and fixed it up a bit.

You can see documentation for it [here](https://github.com/BradleyChatha/jcli/blob/master/source/jaster/cli/core.d#L255), and I've also added an [example](https://github.com/BradleyChatha/jcli/blob/master/examples/09-raw-unparsed-arg-list/source/commands.d) since you've made me realise it was lacking one.

The latest release on dub should have some improvements and fixes, mainly: Before, you had to use a triple dash ("---") since the double dash had some bugs, so I've fixed those bugs and added support for double dash to be used now.

If that's all (e.g. no bugs/issues with the implementation), then I'll close this issue tomorrow/whenever you close it yourself.

**Comment by andrey-zherikov** [comment]
I've looked into the code and found some documentation there. Is it possible to have it somewhere separate and be rendered into a better format (it's hard to navigate through the code and read plain text)? Also is it possible to have more examples in readme or other high-level doc that explains use cases/features so one can easily compare this library with other solutions?

**Comment by BradleyChatha** [comment]
> Is it possible to have it somewhere separate and be rendered into a better format.

Yep, that first link I gave you points to dpldocs.info, a project by [Adam D. Ruppe](https://github.com/adamdruppe) that provides and generates documentation for every dub package, and presents it in a similar style as the official D documentation.

dpldocs is really easy to miss, and I don't find a lot of people talking about it. Maybe I should directly link to it in the README.

> Also is it possible to have more examples in readme or other high-level doc that explains use cases/features?

I definitely do want to do a touch up of the README at some point (maybe today or tomorrow I'll have a look into doing it). My main worry is making the front-page README too large.

e.g. The current one starts off with poorly sized, poorly recorded gifs that aren't actually all that impressive, so I'll either remove/redo them.

e.g. The first text section is a list of JCLI's components, and while it technically does list all of JCLI's features, it's cluttered and hard to read. So I might just make a normal list of features, and then later on the README create a relationship between features and components.

e.g. I feel the Quick Start section is too far down, it should either be the first or second section in my eyes.

And finally, while I do have the [examples](https://github.com/BradleyChatha/jcli/tree/master/examples) folder with documented examples, having a README for that folder (and maybe even each example) could definitely make it easier to approach.

> So one can easily compare this library with other solutions?

I'd need to get myself familiar with a few other solutions, but I like the idea of comparing JCLI's capabilities to other's.

Maybe I should make it its own file, "JCLI compared to so-and-so" comparing features and equivalent code snippets.

I'll definitely have a crack at it sometime this week though, as like I said it's been on my mind for a bit now. Thanks for the suggestion.

**Comment by andrey-zherikov** [comment]
> > Is it possible to have it somewhere separate and be rendered into a better format.
> 
> Yep, that first link I gave you points to dpldocs.info, a project by [Adam D. Ruppe](https://github.com/adamdruppe) that provides and generates documentation for every dub package, and presents it in a similar style as the official D documentation.

I'm personally not fan of dpldocs as I didn't see good documentation for any package (I might miss good example for sure).

> dpldocs is really easy to miss, and I don't find a lot of people talking about it. Maybe I should directly link to it in the README.

This would be useful for sure.

> > So one can easily compare this library with other solutions?
> 
> I'd need to get myself familiar with a few other solutions, but I like the idea of comparing JCLI's capabilities to other's.
> 
> Maybe I should make it its own file, "JCLI compared to so-and-so" comparing features and equivalent code snippets.
> 
> I'll definitely have a crack at it sometime this week though, as like I said it's been on my mind for a bit now. Thanks for the suggestion.

I didn't mean comparing with others explicitly but some list of "how-to" paragraphs that explain how to do certain things. You can look at [std.getopt](https://dlang.org/phobos/std_getopt.html#.getopt) or [python's argparse](https://docs.python.org/3/howto/argparse.html) for example.


In general what made me struggling is that I wanted to quickly understand the capabilities of the library and it turned out that I have to dig into source code/dpldocs to understand what features are available.

**Comment by BradleyChatha** [comment]
After seeing the final part of your reply, it really energised me to fix such a (to me) large issue.

I've made a start over at https://github.com/BradleyChatha/jcli/blob/b57679e76bc6c455393587a88c6b8cd318a5916f/README.md if you wouldn't mind giving it's structure a quick skim.

**Comment by andrey-zherikov** [comment]
I didn't read it thoroughly but it looks much better! And I already see some lack in functionality so I'll create new issues.

PS Feel free to create PR so I can provide some feedback.

**Comment by andrey-zherikov** [comment]
Closing this issue because discussion switched the subject.

**Comment by BradleyChatha** [comment]
Thank you for your time.
