### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by WebFreak001** [BradleyChatha/jcli#56]
I would like to use `ArgConfig.aggregate`, like mentioned in the README, but it doesn't seem to be available in the current release. Can you push a new release? (optionally as beta/alpha release if you don't think it's quite ready for general use yet)

**Comment by BradleyChatha** [comment]
👀 Sure, this poor library's been so neglected that I forgot to even do that.
I'll push it as a beta release since I'm not actually 100% sure what state this is in off the top of my head.

**Comment by BradleyChatha** [comment]
Fixed. I'll go force dub to pick up the tag so you don't have to wait years.

**Comment by andrey-zherikov** [comment]
@WebFreak001 just curious, why not to use [argparse](https://code.dlang.org/packages/argparse)? It has this feature from the very beginning.

**Comment by WebFreak001** [comment]
I'm working with existing code using this library

**Comment by BradleyChatha** [comment]
I do recommend not using JCLI in the future, simply because I just don't have the will to maintain it myself anymore.

More fun and exciting projects to be working on :P
