### ISSUE TITLE
Add @DefaultCommand(string description)

### ISSUE THREAD

**Issue by BradleyChatha** [BradleyChatha/jcli#6]
_Discussion found at https://github.com/BradleyChatha/jcli/pull/5#discussion_r516807169_

* Using `null` is weird and unintuitive, even if it's just a "learn once and get over it" kind of thing.

* Is it worth adding a UDA for this, when only a single default command will appear in most projects? Especially since the command itself can easily be named "DefaultCommand"?

I am leaning towards implementing it, since clarity is definitely something I'd like to have here, but again it's only for a single part of any tool's code that has this weird behaviour.

The default command does have special behaviour and limitations within `CommandLineInterface` though, so it also does make sense to make that difference more explicit beyond "passing null to a UDA".

If I can't think of a good reason *not* to do this by tomorrow, then I'll go ahead and implement it.

**Comment by andrey-zherikov** [comment]
After second thought I'm taking back my comment about `@DefaultCommand` and would suggest to go with `@CommandDefault`. This will match other `@Command*` UDAs
